services:
  backend:
    build:
      context: ./backend
    container_name: pfe-ops-backend
    ports:
      - "18000:8000"
    environment:
      PYTHONUNBUFFERED: "1"
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_NAME: maf_db
      DB_USER: maf_user
      DB_PASSWORD: maf_password
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
      - ./backend/outputs:/app/outputs
      - ./backend/uploads:/app/uploads
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://127.0.0.1:18000/api
    container_name: pfe-ops-frontend
    depends_on:
      - backend
    ports:
      - "15175:15175"
    environment:
      VITE_API_BASE_URL: http://127.0.0.1:18000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules

  mysql:
    image: mysql:8.0
    container_name: maf_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: maf_db
      MYSQL_USER: maf_user
      MYSQL_PASSWORD: maf_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: maf_adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - mysql

  jenkins:
    build:
      context: .
      dockerfile: jenkins/Dockerfile
    container_name: maf_jenkins
    user: root
    restart: unless-stopped
    ports:
      - "18080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace
    working_dir: /workspace
    depends_on:
      - backend
      - frontend
      - mysql
    networks:
      - default

volumes:
  mysql_data:
  jenkins_home: